AWSTemplateFormatVersion: 2010-09-09
Parameters:
  PenguinEnvironment:
    Type: "String"
    Description: "The specified environment for this deployment"
    Default: "cm_penguin_nonprod"
    AllowedValues:
      - cm_penguin_nonprod
      - cm_penguin_staging 
      - cm_penguin_training
      - cm_penguin_preprod
      - cm_penguin_prod
  PenguinApplicationName: 
    Type: "String"
    Default: !Join [ '-', !Ref PenguinEnvironment, "World"]
  PenguinVpc:
    Type: "String"
    Description: "The VPC ID of the environment the app is deploying into."
  PenguinSubnetPublicA:
    Type: "String"
    Description: "The Subnet ID of Public Subnet A"
  PenguinSubnetPublicB:
    Type: "String"
    Description: "The Subnet ID of Public Subnet B"
  PenguinSubnetApplicationA:
    Type: "String"
    Description: "The Subnet ID of Application Subnet A"
  PenguinSubnetApplicationB:
    Type: "String"
    Description: "The Subnet ID of Application Subnet B"
  PenguinSubnetDatabaseA:
    Type: "String"
    Description: "The Subnet ID of Database Subnet A"
  PenguinSubnetDatabaseB:
    Type: "String"
    Description: "The Subnet ID of Database Subnet B"
Resources:

  PenguinApiAlb:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Type: "application"
      IpAddressType: "ipv4"
      Name: ""
      SecurityGroups:
        - ""
      SubnetMappings:
        - ""
      Subnets:
        - ""
      