AWSTemplateFormatVersion: 2010-09-09
Parameters:
  PenguinEnvironment:
    Type: String
    Description: The specified environment for this deployment
    Default: ire-cm-penguin-dev
    AllowedValues:
      - ire-cm-penguin-dev
      - ire-cm-penguin-test2
      - ire-cm-penguin-test3
      - ire-cm-penguin-staging 
      - ire-cm-penguin-training
      - ire-cm-penguin-preprod
      - ire-cm-penguin-prod
  PenguinVpcId:
    Type: String
    Description: "The VPC ID of the environment the app is deploying into."
  
  PenguinApiIamInstanceProfile:
    Type: String
    Description: "The ARN of the IAM Instance Profile to be assigned to this instance"
  
  PenguinApiAmiId:
    Type: String

  PenguinKmsCmkArn:
    Type: String

  PenguinPublicSubnet1Az1:
    Type: String
    Description: "The Subnet ID of Public Subnet A"
  PenguinPublicSubnet1Az2:
    Type: String
    Description: "The Subnet ID of Public Subnet B"

  PenguinPrivateSubnet1Az1:
    Type: String
    Description: "The Subnet ID of Application Subnet A"
  PenguinPrivateSubnet1Az2:
    Type: String
    Description: "The Subnet ID of Application Subnet B"
  
  PenguinPrivateSubnet2Az1:
    Type: String
    Description: "The Subnet ID of Database Subnet A"
  PenguinPrivateSubnet2Az2:
    Type: String
    Description: "The Subnet ID of Database Subnet B"

Mappings:
  PenguinEnvironmentSettings:
    ire-cm-penguin-dev:
      EnvShortName: dev1
      VpcCidr: 10.110.32.0/21
      PublicSubnet1Az1: 10.110.32.0/25
      PublicSubnet1Az2: 10.110.32.128/25
      PrivateSubnet1Az1: 10.110.33.0/25
      PrivateSubnet1Az2: 10.110.33.128/25
      PrivateSubnet2Az1: 10.110.34.0/25
      PrivateSubnet2Az2: 10.110.34.128/25
      PenguinEc2InstanceSize: t3.medium
    ire-cm-penguin-test2:
      EnvShortName: test2
      VpcCidr: 10.110.40.0/21
      PublicSubnet1Az1: 10.110.40.0/25
      PublicSubnet1Az2: 10.110.40.128/25
      PrivateSubnet1Az1: 10.110.41.0/25
      PrivateSubnet1Az2: 10.110.41.128/25
      PrivateSubnet2Az1: 10.110.42.0/25
      PrivateSubnet2Az2: 10.110.42.128/25
      PenguinEc2InstanceSize: t3.medium
    ire-cm-penguin-test3:
      EnvShortName: test3
      VpcCidr: 10.110.48.0/21
      PublicSubnet1Az1: 10.110.48.0/25
      PublicSubnet1Az2: 10.110.48.128/25
      PrivateSubnet1Az1: 10.110.49.0/25
      PrivateSubnet1Az2: 10.110.49.128/25
      PrivateSubnet2Az1: 10.110.50.0/25
      PrivateSubnet2Az2: 10.110.50.128/25
      PenguinEc2InstanceSize: t3.medium
    ire-cm-penguin-staging:
      EnvShortName: staging
      VpcCidr: 10.110.56.0/21
      PublicSubnet1Az1: 10.110.56.0/25
      PublicSubnet1Az2: 10.110.56.128/25
      PrivateSubnet1Az1: 10.110.57.0/25
      PrivateSubnet1Az2: 10.110.57.128/25
      PrivateSubnet2Az1: 10.110.58.0/25
      PrivateSubnet2Az2: 10.110.58.128/25
      PenguinEc2InstanceSize: t3.medium
    ire-cm-penguin-training:
      EnvShortName: training
      VpcCidr: 10.110.16.0/21
      PublicSubnet1Az1: 10.110.16.0/25
      PublicSubnet1Az2: 10.110.16.128/25
      PrivateSubnet1Az1: 10.110.17.0/25
      PrivateSubnet1Az2: 10.110.17.128/25
      PrivateSubnet2Az1: 10.110.18.0/25
      PrivateSubnet2Az2: 10.110.18.128/25
      PenguinEc2InstanceSize: t3.medium
    ire-cm-penguin-preprod:
      EnvShortName: preprod
      VpcCidr: 10.110.8.0/21
      PublicSubnet1Az1: 10.110.8.0/25
      PublicSubnet1Az2: 10.110.8.128/25
      PrivateSubnet1Az1: 10.110.9.0/25
      PrivateSubnet1Az2: 10.110.9.128/25
      PrivateSubnet2Az1: 10.110.10.0/25
      PrivateSubnet2Az2: 10.110.10.128/25
      PenguinEc2InstanceSize: m5.large
    ire-cm-penguin-prod:
      EnvShortName: prod
      VpcCidr: 10.110.0.0/21
      PublicSubnet1Az1: 10.110.0.0/25
      PublicSubnet1Az2: 10.110.0.128/25
      PrivateSubnet1Az1: 10.110.1.0/25
      PrivateSubnet1Az2: 10.110.1.128/25
      PrivateSubnet2Az1: 10.110.2.0/25
      PrivateSubnet2Az2: 10.110.2.128/25
      PenguinEc2InstanceSize: m5.large

Resources:
  PenguinPublicAlbSecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Access rules and definitions for the Primary Penguin Public API ALB
      GroupName: PenguinPublicAlbSecurityGroup
      VpcId: 
        Ref: PenguinVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
  
  PenguinApplicationSecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Access rules and definitions for Penguin Application Servers
      GroupName: PenguinApplicationSecurityGroup
      VpcId: 
        Ref: PenguinVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroup:
            Ref: PenguinPublicAlbSecGroup

  PenguinApiAlb:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Type: "application"
      IpAddressType: "ipv4"
      Name: ""
      SecurityGroups:
        - ""
      SubnetMappings:
        - ""
      Subnets:
        - ""
  PenguinApiLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: "IRE-CM-Penguin-API"
      LaunchTemplateData:
        ImageId: PenguinApiAmiId
        InstanceType: !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, PenguinEc2InstanceSize]
        IamInstanceProfile:
          Arn: !Ref PenguinApiIamInstanceProfile
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: false
            DeleteOnTermination: true
            Groups:
              - !Ref PenguinPublicAlbSecGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: IRE-CM-Penguin-API
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 100
              VolumeType: gp2
              DeleteOnTermination: true
              Encrypted: true
              KmsKeyId: !Ref PenguinKmsCmkArn
        UserData: !Base64 
          'Fn::Sub': >
            %POWERSHELL_SCRIPT%
