AWSTemplateFormatVersion: 2010-09-09
Metadata:
  Project: CoverMore EMEA Migration to AMS
  Author: Brandon Pierce <brandon.pierce@slalom.com>
  Version: 0.2.1
  Date-Created: 2020-11-30 23:36

Parameters:
  PenguinEnvironment:
    Type: String
    Description: The specified environment for this deployment
    Default: ire-cm-penguin-dev
    AllowedValues:
      - ire-cm-penguin-dev
      - ire-cm-penguin-test2
      - ire-cm-penguin-test3
      - ire-cm-penguin-staging 
      - ire-cm-penguin-training
      - ire-cm-penguin-preprod
      - ire-cm-penguin-prod
  
  PenguinVpcId:
    Type: String
    Description: "The VPC ID of the environment the app is deploying into."
  
  PenguinDatabaseIamInstanceProfile:
    Type: String
    Description: "The ARN of the IAM Instance Profile to be assigned to this instance"

  PenguinKmsCmkArn:
    Description: "The KMS CMK ARN of the key created for this Penguin application environment."
    Type: String
  
  PenguinDbAmiId:
    Type: String
    Description: "The AMI of the AMS SOE image."

  PenguinPrivateHostedZone:
    Description: "The Route 53 private hosted zone ID of the application account hosted zone."
    Type: String

  PenguinDatabaseSubnetIdAz1:
    Type: String
    Description: "The Subnet ID of Database Subnet A"

  PenguinDatabaseSubnetIdAz2:
    Type: String
    Description: "The Subnet ID of Database Subnet B"

  SharedServicesCidr:
    Type: String
    Description: "The VPC CIDR for MALZ Shared Services account"
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    Default: 10.109.2.0/23

Mappings:
  PenguinEnvironmentSettings:
    ire-cm-penguin-dev:
      EnvShortName: dev
      VpcCidr: 10.110.32.0/21
      PublicSubnet1Az1: 10.110.32.0/25
      PublicSubnet1Az2: 10.110.32.128/25
      ApplicationSubnetAz1: 10.110.33.0/25
      ApplicationSubnetAz2: 10.110.33.128/25
      DatabaseSubnetAz1: 10.110.34.0/25
      DatabaseSubnetAz2: 10.110.34.128/25
      PenguinEc2InstanceSize: t3.xlarge
      DatabaseVolumeSize: 100
      LogRetentionInDays: 7

    ire-cm-penguin-test2:
      EnvShortName: test2
      VpcCidr: 10.110.40.0/21
      PublicSubnet1Az1: 10.110.40.0/25
      PublicSubnet1Az2: 10.110.40.128/25
      ApplicationSubnetAz1: 10.110.41.0/25
      ApplicationSubnetAz2: 10.110.41.128/25
      DatabaseSubnetAz1: 10.110.42.0/25
      DatabaseSubnetAz2: 10.110.42.128/25
      PenguinEc2InstanceSize: t3.xlarge
      DatabaseVolumeSize: 100
      LogRetentionInDays: 7
      
    ire-cm-penguin-test3:
      EnvShortName: test3
      VpcCidr: 10.110.48.0/21
      PublicSubnet1Az1: 10.110.48.0/25
      PublicSubnet1Az2: 10.110.48.128/25
      ApplicationSubnetAz1: 10.110.49.0/25
      ApplicationSubnetAz2: 10.110.49.128/25
      DatabaseSubnetAz1: 10.110.50.0/25
      DatabaseSubnetAz2: 10.110.50.128/25
      PenguinEc2InstanceSize: t3.xlarge
      DatabaseVolumeSize: 100
      LogRetentionInDays: 7

    ire-cm-penguin-staging:
      EnvShortName: staging
      VpcCidr: 10.110.56.0/21
      PublicSubnet1Az1: 10.110.56.0/25
      PublicSubnet1Az2: 10.110.56.128/25
      ApplicationSubnetAz1: 10.110.57.0/25
      ApplicationSubnetAz2: 10.110.57.128/25
      DatabaseSubnetAz1: 10.110.58.0/25
      DatabaseSubnetAz2: 10.110.58.128/25
      PenguinEc2InstanceSize: t3.xlarge
      DatabaseVolumeSize: 100
      LogRetentionInDays: 7

    ire-cm-penguin-training:
      EnvShortName: training
      VpcCidr: 10.110.16.0/21
      PublicSubnet1Az1: 10.110.16.0/25
      PublicSubnet1Az2: 10.110.16.128/25
      ApplicationSubnetAz1: 10.110.17.0/25
      ApplicationSubnetAz2: 10.110.17.128/25
      DatabaseSubnetAz1: 10.110.18.0/25
      DatabaseSubnetAz2: 10.110.18.128/25
      PenguinEc2InstanceSize: t3.xlarge
      DatabaseVolumeSize: 100
      LogRetentionInDays: 7

    ire-cm-penguin-preprod:
      EnvShortName: preprod
      VpcCidr: 10.110.8.0/21
      PublicSubnet1Az1: 10.110.8.0/25
      PublicSubnet1Az2: 10.110.8.128/25
      ApplicationSubnetAz1: 10.110.9.0/25
      ApplicationSubnetAz2: 10.110.9.128/25
      DatabaseSubnetAz1: 10.110.10.0/25
      DatabaseSubnetAz2: 10.110.10.128/25
      PenguinEc2InstanceSize: m5.large
      DatabaseVolumeSize: 100
      LogRetentionInDays: 7

    ire-cm-penguin-prod:
      EnvShortName: prod
      VpcCidr: 10.110.0.0/21
      PublicSubnet1Az1: 10.110.0.0/25
      PublicSubnet1Az2: 10.110.0.128/25
      ApplicationSubnetAz1: 10.110.1.0/25
      ApplicationSubnetAz2: 10.110.1.128/25
      DatabaseSubnetAz1: 10.110.2.0/25
      DatabaseSubnetAz2: 10.110.2.128/25
      PenguinEc2InstanceSize: m5.large
      DatabaseVolumeSize: 150
      LogRetentionInDays: 7

Conditions:
  ProvisionForProd: !Equals [!FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, EnvShortName], prod]

Resources:
  PenguinDatabaseSecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Access rules and definitions for the Penguin Databases
      GroupName: !Join ["-", ["IRE-CM-Penguin", !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, EnvShortName], "Database-Security-Group"]]
      VpcId: !Ref PenguinVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          Description: Allow on-prem systems to access environment database servers
          FromPort: 1433
          ToPort: 1433
          CidrIp: 10.2.0.0/24
        - IpProtocol: tcp
          Description: Allow connections from Application Subnet1
          FromPort: 1433
          ToPort: 1433
          CidrIp: !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, ApplicationSubnetAz1]
        - IpProtocol: tcp
          Description: Allow connections from Application Subnet2
          FromPort: 1433
          ToPort: 1433
          CidrIp: !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, ApplicationSubnetAz2]
        - IpProtocol: tcp
          Description: "Comms from Octopus code deployment"
          FromPort: 10933
          ToPort: 10933
          CidrIp: 10.200.20.120/32
        - IpProtocol: tcp
          Description: "Comms from Octopus code deployment"
          FromPort: 10943
          ToPort: 10943
          CidrIp: 10.200.20.120/32
        - IpProtocol: tcp
          Description: "Comms from Octopus code deployment -- likely redundant to be investigated"
          FromPort: 80
          ToPort: 80
          CidrIp: 10.200.20.120/32
        - IpProtocol: tcp
          Description: "Comms from Octopus code deployment -- likely redundant to be investigated"
          FromPort: 443
          ToPort: 443
          CidrIp: 10.200.20.120/32
      SecurityGroupEgress:
        - IpProtocol: tcp
          Description: Allow connections from Application Subnet2
          FromPort: 1433
          ToPort: 1433
          CidrIp: 10.2.0.0/24
        - IpProtocol: tcp
          Description: Allow DB servers to communicate with the internet
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          Description: Allow DB servers to communicate with the internet
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          Description: "Comms to Octopus code deployment"
          FromPort: 10943
          ToPort: 10943
          CidrIp: 10.200.20.120/32
        - IpProtocol: "-1"
          FromPort: -1
          ToPort: -1
          Description: "Allow all Comms to Shared Services"
          CidrIp: !Ref SharedServicesCidr
      Tags:
        - Key: Name
          Value: !Join ["-", ["IRE-CM-Penguin", !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, EnvShortName], "Database-Security-Group"]]

  PenguinDatabaseLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateData:
        CreditSpecification:
          CpuCredits: unlimited
        ImageId: !Ref PenguinDbAmiId
        InstanceType: !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, PenguinEc2InstanceSize]
        IamInstanceProfile:
          Arn: !Ref PenguinDatabaseIamInstanceProfile
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, DatabaseVolumeSize]
              VolumeType: gp2
              DeleteOnTermination: true
              Encrypted: true
              KmsKeyId: !Ref PenguinKmsCmkArn
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Join ["-", ["IRE-CM-Penguin", !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, EnvShortName], "Database-Server"]]

  PenguinDatabasePrimary:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref PenguinDatabaseLaunchTemplate
        Version: !GetAtt [PenguinDatabaseLaunchTemplate, LatestVersionNumber]
      SecurityGroupIds: 
      - !Ref PenguinDatabaseSecGroup
      SubnetId: !Ref PenguinDatabaseSubnetIdAz1

  PenguinDatabaseSecondaryA:
    Type: AWS::EC2::Instance
    Condition: ProvisionForProd
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref PenguinDatabaseLaunchTemplate
        Version: !GetAtt [PenguinDatabaseLaunchTemplate, LatestVersionNumber]
      SecurityGroupIds: 
      - !Ref PenguinDatabaseSecGroup
      SubnetId: !Ref PenguinDatabaseSubnetIdAz2

  PenguinDatabaseSecondaryB:
    Type: AWS::EC2::Instance
    Condition: ProvisionForProd
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref PenguinDatabaseLaunchTemplate
        Version: !GetAtt [PenguinDatabaseLaunchTemplate, LatestVersionNumber]
      SecurityGroupIds: 
      - !Ref PenguinDatabaseSecGroup
      SubnetId: !Ref PenguinDatabaseSubnetIdAz1
  
  PenguinDatabasePrimaryRoute53Record:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Join [".", ["dbprimary", !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, EnvShortName], "penguin.aws-pri.covermore.co.uk"]]
      Type: A
      ResourceRecords:
      - !GetAtt PenguinDatabasePrimary.PrivateIp
      HostedZoneId: !Ref PenguinPrivateHostedZone

  PenguinDatabaseSecondaryARoute53Record:
    Type: 'AWS::Route53::RecordSet'
    Condition: ProvisionForProd
    Properties:
      Name: !Join [".", ["dbsecondarya", !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, EnvShortName], "penguin.aws-pri.covermore.co.uk"]]
      Type: A
      ResourceRecords:
      - !GetAtt PenguinDatabaseSecondaryA.PrivateIp
      HostedZoneId: !Ref PenguinPrivateHostedZone

  PenguinDatabaseSecondaryBRoute53Record:
    Type: 'AWS::Route53::RecordSet'
    Condition: ProvisionForProd
    Properties:
      Name: !Join [".", ["dbsecondaryb", !FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, EnvShortName], "penguin.aws-pri.covermore.co.uk"]]
      Type: A
      ResourceRecords:
      - !GetAtt PenguinDatabaseSecondaryB.PrivateIp
      HostedZoneId: !Ref PenguinPrivateHostedZone