AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PenguinEnvironment:
    Type: "String"
    Description: "The specified environment for this deployment"
    Default: "cm_penguin_nonprod"
    AllowedValues:
      - cm_penguin_nonprod
      - cm_penguin_staging 
      - cm_penguin_training
      - cm_penguin_preprod
      - cm_penguin_prod
  PenguinApplicationName:
    Type: String
    Default: !Join [ '-', !Ref PenguinEnvironment, "World"]
  PenguinVpc:
    Type: String
    Description: "The VPC ID of the environment the app is deploying into."

Resources:
  PenguinDatabaseSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Access rules and definitions for Penguin Application Servers
      GroupName: PenguinApplicationSecurityGroup
      VpcId: 
        Ref: PenguinVpc