AWSTemplateFormatVersion: 2010-09-09
Parameters:
  PenguinEnvironment:
    Type: String
    Description: The specified environment for this deployment
    Default: ire-cm-penguin-dev
    AllowedValues:
      - ire-cm-penguin-dev
      - ire-cm-penguin-test2
      - ire-cm-penguin-test3
      - ire-cm-penguin-staging 
      - ire-cm-penguin-training
      - ire-cm-penguin-preprod
      - ire-cm-penguin-prod
  
  PenguinVpcId:
    Type: String
    Description: "The VPC ID of the environment the app is deploying into."
    
  PenguinVpcRegion:
    Type: String
    Description: "The VPC region of the environment the app is deploying into."
    Default: eu-west-1

Mappings:
  PenguinEnvironmentSettings:
    ire-cm-penguin-dev:
      EnvShortName: dev1
    ire-cm-penguin-test2:
      EnvShortName: test2
    ire-cm-penguin-test3:
      EnvShortName: test3
    ire-cm-penguin-staging:
      EnvShortName: staging
    ire-cm-penguin-training:
      EnvShortName: training
    ire-cm-penguin-preprod:
      EnvShortName: preprod
    ire-cm-penguin-prod:
      EnvShortName: prod

Resources:
  PenguinDnsExternalHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: IRE-CM-Penguin AWS HostedZone
      Name: !Join ['.', [!FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, EnvShortName], 'penguin', 'aws-ext', 'covermore.co.uk']]
  
  PenguinDnsInternalHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: IRE-CM-Penguin AWS HostedZone
      Name: !Join ['.', [!FindInMap [PenguinEnvironmentSettings, !Ref PenguinEnvironment, EnvShortName], 'penguin', 'aws-int', 'covermore.co.uk']]
      VPCs:
        -
          VPCId: !Ref PenguinVpcId
          VPCRegion: !Ref PenguinVpcRegion
Outputs:
  PenguinDnsExternalHostedZoneNsRecords:
    Description: The Environment external HostedZone NS Server setting values for parent delegation
    Value: !Join [ ',', !GetAtt PenguinDnsExternalHostedZone.NameServers]
  PenguinDnsExternalHostedZoneId:
    Description: "The Environment external HostedZone record ID"
    Value: !Ref PenguinDnsExternalHostedZone

  PenguinDnsInternalHostedZoneId:
    Description: "The Environment internal HostedZone record ID"
    Value: !Ref PenguinDnsInternalHostedZone